name       : python-rebulk
version    : 3.1.0
release    : 8
source     :
    - https://github.com/Toilal/rebulk/releases/download/v3.1.0/rebulk-3.1.0.tar.gz : 809de3a97c68afa831f7101b10d316fe62e061dc9f7f67a44b7738128721173a
homepage   : https://github.com/Toilal/rebulk
license    :
    - Apache-2.0
    - MIT
component  : programming.python
summary    : Define simple search patterns in bulk to perform advanced matching on any string
description: |
    ReBulk is a python library that performs advanced searches in strings that would be hard to implement using re module or String methods only. It includes some features like Patterns, Match, Rule that allows developers to build a custom and complex string matcher using a readable and extendable API.
builddeps  :
    - pylint # check
    - pytest-runner # check
rundeps    :
    - python-regex
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
