name       : python-rebulk
version    : 0.7.6
release    : 1
source     :
    - https://pypi.python.org/packages/1b/e6/ff6bab7e66679a01ea52b0269a354df3a8047572eac107fff70110f5d943/rebulk-0.7.6.tar.gz : 1357820b13460fc30ecdf58b7743b34da79f76bec954c21051da9eefab0e82cd
license    : MIT
component  : programming.python
summary    : Define simple search patterns in bulk to perform advanced matching on any string.
description: |
    Define simple search patterns in bulk to perform advanced matching on any string.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
