name       : python-rebulk
version    : 1.0.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/r/rebulk/rebulk-1.0.0.tar.gz : 1d49e4f7ef6fb874e60efccacbbe661092fabdb7770cdf7f7de4516d50535998
license    :
    - Apache-2.0
    - MIT
component  : programming.python
summary    : Define simple search patterns in bulk to perform advanced matching on any string
description: |
    ReBulk is a python library that performs advanced searches in strings that would be hard to implement using re module or String methods only.
    
    It includes some features like Patterns, Match, Rule that allows developers to build a custom and complex string matcher using a readable and extendable API.
builddeps  :
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
